postgres:
    image: postgres:9.4.5
    environment:
        - POSTGRES_USER=youruser
        - POSTGRES_PASSWORD=yourpw
    ports:
        - "5432:5432"
elasticsearch:
    image: elasticsearch:1.4.5
    environment:
        ELASTICSEARCH_USER: youruser
        ELASTICSEARCH_PASS: yourpw
    ports:
        - "9200:9200"
